[octomap_server] Enable for building color octomap server
OctoMap/octomap_mapping pull request #35
Opened 2016-08-30 16:52 UTC by wkentaro

2019-01-27 23:24 UTC, wxmerkt requested changes
Thank you very much for the improvement to get the colour without the byte shift! Can you please revert the change to the `#DEFINE` - very happy to merge this pull request then :)

2019-01-27 23:24 UTC, wxmerkt commented on octomap_server/include/octomap_server/OctomapServer.h
> +#define COLOR_OCTOMAP_SERVER
Can you please deactivate this define? We do not want to change default behaviour.

2019-01-27 23:44 UTC, wxmerkt commented
Thank you @wkentaro! 

I have just changed the base branch to `kinetic-devel` and it appears there are conflicts. Could you please have a look and resolve? [We are now developing against kinetic-devel by default]

2019-01-28 10:59 UTC, wkentaro commented
Fixed.

2019-01-28 11:25 UTC, wxmerkt approved these changes
Thank you! Will merge once it passes CI.

2019-01-28 12:24 UTC, merged