Add color server nodelet support
OctoMap/octomap_mapping pull request #67
Opened 2020-04-11 14:57 UTC by clunietp

Added support for running color server as a nodelet.  Tested on melodic

2020-04-11 15:24 UTC, wxmerkt requested changes

2020-04-11 15:24 UTC, wxmerkt commented on octomap_server/CMakeLists.txt
> +add_library(octomap_color_server_nodelet src/octomap_server_nodelet.cpp)
Thank you for your contribution. Can you please also add this nodelet to the `install` command below?

Thank you!

2020-04-11 17:56 UTC, merged

2020-04-11 17:56 UTC, wxmerkt commented
Thank you for your contribution!

2020-04-11 22:50 UTC, clunietp commented
Thank you @wxmerkt !

2020-04-12 12:58 UTC, clunietp commented
@wxmerkt , I just noticed this in `octomap_mapping/CMakeLists.txt`:

    install(FILES nodelet_plugins.xml
    DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})

I'm assuming we'd want to add `color_nodelet_plugins.xml` to this as well?

2020-04-12 13:00 UTC, wxmerkt commented
Yes, please. Thanks for spotting!